---
- hosts: all
  gather_facts: True
  tasks:
    - name: reset | remove all docker images
      shell: "/usr/bin/docker image ls -a -q | xargs -r /usr/bin/docker rmi -f"
      retries: 2
      delay: 5
      tags:
        - docker
    - name: reset | remove docker itself
      shell: "apt-get purge docker-* -y --allow-change-held-packages"
      retries: 2
      delay: 30
      tags:
        - docker