    ProjectName: proj1
    ClusterProvider: provider1
    Cluster1: cluster1
    ClusterLabel: edge-cluster
    ClusterLabelNetworkPolicy: networkpolicy-supported
    AdminCloud: default
    CompositeApp: prometheus-collectd-composite-app
    App1: prometheus-operator
    App2: collectd
    App3: operator
    App4: http-client
    App5: http-server
    KubeConfig: /root/c01.config
    HelmApp1: output/prometheus-operator.tar.gz
    HelmApp2: output/collectd.tar.gz
    HelmApp3: output/operator.tar.gz
    HelmApp4: output/http-client.tar.gz
    HelmApp5: output/http-server.tar.gz
    HelmAppFirewall: output/firewall.tar.gz
    HelmAppPacketgen: output/packetgen.tar.gz
    HelmAppSink: output/sink.tar.gz
    ProfileFw: output/profile.tar.gz
    ProfileApp1: output/prometheus-operator_profile.tar.gz
    ProfileApp2: output/collectd_profile.tar.gz
    ProfileApp3: output/operator_profile.tar.gz
    ProfileApp4: output/http-client-profile.tar.gz
    ProfileApp5: output/http-server-profile.tar.gz
    CompositeProfile: collection-composite-profile
    GenericPlacementIntent: collection-placement-intent
    DeploymentIntent: collection-deployment-intent-group
    RsyncPort: 9031
    CompositeAppGac: gac-composite-app
    GacIntent: collectd-gac-intent
    CompositeAppDtc: dtc-composite-app
    DtcIntent: collectd-dtc-intent
    ConfigmapFile: info.json
    HostIP: localhost